1 rem - cre8words, a basic program to create a relative file containing
2 rem - 5756 words for logos64; written by Miles Dyck, November 2022
7900 rem - prior to running the program, the words.rel file can be
7901 rem - created using live basic with the following commands:
7902 rem - open15,8,15
7903 rem - open2,8,2,"words,l,"+chrs$(6)
7904 rem - print#15,"p"+chr$(96+2)+chr$(124)+chr$(22)+chr$(1)
7905 rem - print#2,"zowie";
7906 rem - close2
7907 rem - close15
7908 rem - ignore the blinking disk drive light
7909 rem - each record in the words.rel file is 6 characters, 5 letters
7910 rem - plus a carriage return [chr$(13)] 
7911 rem - a helpful tutorial on relative files can be found here:
7912 rem - https://www.atarimagazines.com/compute/issue40/relative_files.php 
8000 open3,8,4,"words"
8010 open15,8,15
8012 rem - r1% is the high index for the record and r2% is the low index
8014 rem - r1% ranges between 0 & 255; r2% ranges between 0 & 22
8015 r1%=0
8020 fork=1to5756
8022 readn$
8025 r2%=int(k/256):r1%=r1%+1
8027 ifr1%=256thenr1%=0
8030 print#15,"p"+chr$(100)+chr$(r1%)+chr$(r2%)+chr$(1)
8032 rem - k is the record number, r1% and r2% the high/low indices and
8034 rem - n$ the word read from the data list below
8035 print k,r1%,r2%,n$
8040 print#3,n$;
8070 nextk
8080 close3
8100 close15:end
20000 data aargh,abaca,abaci,aback,abaft,abase,abash,abate,abbey,abbot,abeam
20010 data abend,abets,abhor,abide,abled,abler,abode,abort,about,above,absit
20020 data abuse,abuts,abuzz,abyss,ached,aches,achoo,acids,acing,acked,acmes
20030 data acned,acnes,acorn,acres,acrid,acted,actin,actor,acute,adage,adapt
20040 data added,adder,addle,adept,adieu,adios,adlib,adman,admen,admit,admix
20050 data adobe,adopt,adore,adorn,adult,adzes,aegis,aerie,affix,afire,afoot
20060 data afore,afoul,after,again,agape,agars,agate,agave,agent,agile,aging
20070 data agley,aglow,agone,agony,agora,agree,agues,ahead,ahold,ahoys,aided
20080 data aider,aides,ailed,aimed,aimer,aioli,aired,airer,aisle,aitch,ajuga
20090 data alack,alarm,album,alder,aleck,aleph,alert,algae,algal,algin,alias
20100 data alibi,alien,align,alike,alive,alkyd,alkyl,allay,alley,allot,allow
20110 data alloy,aloes,aloft,aloha,alone,along,aloof,aloud,alpha,altar,alter
20120 data altho,altos,alums,alway,amahs,amass,amaze,amber,ambit,amble,ameba
20130 data amend,amens,amide,amigo,amine,amino,amiss,amity,ammos,among,amour
20140 data amped,ample,amply,amuck,amuse,amyls,anded,anent,angel,anger,angle
20150 data angry,angst,anile,anima,anion,anise,ankhs,ankle,annas,annex,annoy
20160 data annul,annum,anode,anole,anted,antes,antic,antis,antsy,anvil,aorta
20170 data apace,apart,apers,aphid,aphis,apian,aping,apish,apnea,aport,apple
20180 data apply,apron,apses,apsos,aptly,aquae,aquas,arbor,arced,ardor,areal
20190 data areas,arena,argon,argot,argue,arias,arise,arity,armed,armor,aroma
20200 data arose,arras,array,arrow,arses,arson,artsy,arums,asana,ascot,ashen
20210 data ashes,aside,asked,asker,askew,aspen,aspic,assai,assay,assed,asses
20220 data asset,aster,astir,astro,atilt,atlas,atoll,atoms,atone,atria,attar
20230 data attic,audio,audit,auger,aught,augur,aunts,aurae,aural,auras,auric
20240 data autos,avail,avant,avast,avers,avert,avian,avoid,avows,await,awake
20250 data award,aware,awash,aways,awful,awing,awoke,axels,axial,axing,axiom
20260 data axled,axles,axman,axmen,axons,ayins,azine,azoic,azure,babel,babes
20270 data backs,bacon,baddy,badge,badly,bagel,baggy,bahts,bails,bairn,baits
20280 data baize,baked,baker,bakes,balds,baldy,baled,baler,bales,balks,balky
20290 data balls,bally,balms,balmy,balsa,banal,bands,bandy,banes,bangs,banjo
20300 data banks,banns,barbs,bards,bared,barer,bares,barfs,barfy,barge,baric
20310 data barks,barky,barms,barmy,barns,baron,basal,based,baser,bases,basic
20320 data basil,basin,basis,basks,bassi,basso,baste,batch,bated,bates,bathe
20330 data baths,batik,baton,batty,bauds,baulk,bawdy,bawls,bayed,bayou,bazar
20340 data beach,beads,beady,beaks,beaky,beams,beamy,beano,beans,beard,bears
20350 data beast,beats,beaus,beaut,beaux,bebop,bebug,becks,bedew,bedim,beech
20360 data beefs,beefy,beeps,beers,beery,beets,befit,befog,began,begat,beget
20370 data begin,begot,begun,beige,being,belay,belch,belie,belle,belli,bells
20380 data belly,below,belts,bench,bends,bents,beret,bergs,berms,berry,berth
20390 data beryl,beset,besot,bests,betas,betel,beths,bevel,bezel,bhang,bhoys
20400 data bibbs,bible,biddy,bided,bider,bides,bidet,biers,biffs,biffy,biggy
20410 data bight,bigly,bigot,biked,biker,bikes,biles,bilge,bilgy,bilks,bills
20420 data billy,bimbo,binds,binge,bingo,biome,biped,bipod,birch,birds,birth
20430 data bison,bitch,biter,bites,bitsy,bitty,blabs,black,blade,blahs,blame
20440 data bland,blank,blare,blash,blast,blats,blaze,bleak,blear,bleat,blebs
20450 data bleed,blend,bless,blest,blimp,blind,blini,blink,blips,bliss,blitz
20460 data bloat,blobs,block,blocs,bloke,blond,blood,bloom,blots,blown,blows
20470 data blowy,blued,bluer,blues,bluff,blunt,blurb,blurs,blurt,blush,board
20480 data boars,boast,boats,bobby,bocce,bocci,bocks,boded,bodes,bodge,boffo
20490 data boffs,bogey,boggy,bogie,bogus,boils,bolas,bolls,bolos,bolts,bombe
20500 data bombs,bonds,boned,boner,bones,bongo,bongs,bonks,bonne,bonny,bonus
20510 data boobs,booby,booed,books,booky,booms,boomy,boons,boors,boost,booth
20520 data boots,booty,booze,boozy,borax,bored,borer,bores,boric,borne,boron
20530 data bosky,bosom,boson,bossa,bossy,bosun,botch,bough,boule,bound,bouts
20540 data bowed,bowel,bower,bowie,bowls,boxed,boxer,boxes,bozos,brace,brack
20550 data bract,brads,braes,brags,braid,brain,brake,brand,brans,brant,brash
20560 data brass,brats,brava,brave,bravo,brawl,brawn,brays,braze,bread,break
20570 data bream,breed,brent,breve,brews,briar,bribe,brick,bride,brief,brier
20580 data bries,brigs,brims,brine,bring,brink,briny,brisk,broad,broil,broke
20590 data bromo,bronc,bronx,brood,brook,broom,broth,brown,brows,bruin,bruit
20600 data brung,brunt,brush,brusk,brute,bubba,bucks,buddy,budge,buena,bueno
20610 data buffa,buffo,buffs,buggy,bugle,build,built,bulbs,bulge,bulgy,bulks
20620 data bulky,bulls,bully,bumph,bumps,bumpy,bunch,bunco,bunds,bungs,bunko
20630 data bunks,bunny,bunts,buoys,buret,burgs,burls,burly,burns,burnt,burps
20640 data burro,burrs,burry,burst,busby,bused,buses,bushy,busks,busts,busty
20650 data butch,butte,butts,butyl,buxom,buyer,buzzy,bwana,bylaw,byres,bytes
20660 data byway,cabal,cabby,cabin,cable,cacao,cache,cacti,caddy,cadet,cadge
20670 data cadre,cafes,caged,cager,cages,cagey,cairn,caked,cakes,calix,calks
20680 data calla,calls,calms,calve,calyx,camel,cameo,campo,camps,campy,canal
20690 data candy,caned,caner,canes,canna,canny,canoe,canon,canst,canto,cants
20700 data caped,caper,capes,capon,capos,carat,cards,cared,carer,cares,caret
20710 data cargo,carne,carny,carob,carol,carom,caron,carps,carpy,carry,carte
20720 data carts,carve,casas,cased,cases,casks,caste,casts,casus,catch,cater
20730 data catty,caulk,cauls,cause,caved,caves,cavil,cawed,cease,cedar,ceded
20740 data ceder,cedes,ceils,celeb,cello,cells,cento,cents,chafe,chaff,chain
20750 data chair,chalk,champ,chant,chaos,chaps,chard,charm,chars,chart,chary
20760 data chase,chasm,chats,chaws,cheap,cheat,check,cheek,cheep,cheer,chefs
20770 data chert,chess,chest,chews,chewy,chick,chide,chief,chiff,child,chile
20780 data chili,chill,chime,chimp,china,chine,chink,chino,chins,chips,chirp
20790 data chits,chive,chock,choir,choke,chomp,choos,chops,chord,chore,chose
20800 data chows,chuck,chuff,chugs,chump,chums,chunk,churl,churn,chute,cider
20810 data cigar,cilia,cills,cinch,circa,cirri,cited,cites,civet,civic,civil
20820 data civvy,clack,clads,claim,clamp,clams,clang,clank,clans,claps,clash
20830 data clasp,class,clave,claws,clays,clean,clear,cleat,clefs,cleft,clerk
20840 data clews,click,cliff,climb,clime,cling,clink,clips,cloak,clock,clods
20850 data clogs,clomp,clone,clops,close,cloth,clots,cloud,clout,clove,clown
20860 data cloys,clubs,cluck,clued,clues,clump,clung,clunk,coach,coals,coast
20870 data coati,coats,cobra,cocas,cocci,cocks,cocky,cocoa,cocos,codas,coded
20880 data coder,codes,codex,codon,coeds,cohos,coifs,coils,coins,coked,cokes
20890 data colas,colds,colic,colon,color,colts,comas,combo,combs,comer,comes
20900 data comet,comfy,comic,comma,comps,conch,condo,coned,cones,coney,conga
20910 data conic,conks,cooch,cooed,cooks,cooky,cools,coons,coops,coots,coped
20920 data coper,copes,copra,copse,coqui,coral,cords,cordy,cored,corer,cores
20930 data corgi,corks,corky,corms,corns,cornu,corny,corps,coset,costa,costs
20940 data cotes,cotta,couch,cough,could,count,coupe,coups,court,couth,coven
20950 data cover,coves,covet,covey,cowed,cower,cowls,cowry,coxed,coxes,coyer
20960 data coyly,coypu,cozen,crabs,crack,craft,crags,cramp,crams,crane,crank
20970 data craps,crash,crass,crate,crave,crawl,craws,craze,crazy,creak,cream
20980 data credo,creed,creek,creel,creep,creme,crepe,crept,cress,crest,crews
20990 data cribs,crick,cried,crier,cries,crime,crimp,crink,crisp,crits,croak
21000 data crock,crocs,croft,crone,crony,crook,croon,crops,cross,croup,crowd
21010 data crown,crows,crude,cruds,cruel,cruet,cruft,crumb,crump,cruse,crush
21020 data crust,crypt,cubby,cubed,cuber,cubes,cubic,cubit,cuffs,cuing,cukes
21030 data culls,culpa,cults,cumin,cunts,cupid,cuppa,cuppy,curbs,curds,curdy
21040 data cured,curer,cures,curia,curie,curio,curls,curly,curry,curse,curve
21050 data curvy,cushy,cusps,cuspy,cuter,cutie,cutup,cycad,cycle,cynic,cysts
21060 data czars,dacha,daddy,dados,daffy,daily,dairy,daisy,dales,dally,dames
21070 data damns,damps,dance,dandy,dared,darer,dares,darks,darky,darns,darts
21080 data dashy,dated,dater,dates,datum,daubs,daunt,davit,dawns,dazed,dazes
21090 data deads,deals,dealt,deans,dears,deary,death,debar,debit,debts,debug
21100 data debut,decaf,decal,decay,decks,decor,decoy,decry,deeds,deems,deeps
21110 data defer,defog,defun,degas,degum,deice,deify,deign,deism,deist,deity
21120 data delay,delft,delis,dells,delta,delve,demit,demon,demos,demur,denim
21130 data dense,dents,depot,depth,deque,derby,desex,desks,deter,deuce,devil
21140 data dewed,dewey,dhows,dials,diary,diazo,diced,dicer,dices,dicey,dicks
21150 data dicky,dicot,dicta,dictu,dicut,diddy,didos,didot,didst,diems,diest
21160 data dieth,diets,digit,diked,dikes,dildo,dills,dilly,dimer,dimes,dimly
21170 data dinar,dined,diner,dines,dingo,dings,dingy,dinks,dinky,dints,diode
21180 data dippy,dipso,direr,dirge,dirks,dirts,dirty,disco,discs,dishy,disks
21190 data ditch,ditto,ditty,divan,divas,dived,diver,dives,divot,divvy,dixit
21200 data dizzy,djinn,docks,dodge,dodgy,dodos,doers,doest,doeth,doffs,doges
21210 data doggo,doggy,dogie,dogma,doily,doing,dolce,doled,doles,dolls,dolly
21220 data dolor,dolts,domed,domes,donee,donna,donor,donut,dooms,doors,doozy
21230 data doped,doper,dopes,dopey,dorks,dorky,dorms,dosed,doser,doses,doted
21240 data doter,dotes,dotty,doubt,dough,douse,doves,dovey,dowdy,dowel,dower
21250 data downs,downy,dowry,dowse,doxie,doyen,dozed,dozen,dozer,dozes,drabs
21260 data draft,drags,drain,drake,drama,drams,drank,drape,drawl,drawn,draws
21270 data drays,dread,dream,drear,dreck,dregs,dress,dribs,dried,drier,dries
21280 data drift,drill,drily,drink,drips,drive,droid,droll,drone,drool,droop
21290 data drops,dross,drove,drown,drubs,drugs,druid,drums,drunk,dryad,dryer
21300 data dryly,duals,ducal,ducat,duces,duchy,ducks,ducky,ducts,duddy,dudes
21310 data duels,duets,duffs,dukes,dulls,dully,dulse,dummy,dumps,dumpy,dunce
21320 data dunes,dungs,dungy,dunks,dunno,duomo,duped,duper,dupes,duple,durst
21330 data dusks,dusky,dusts,dusty,dutch,duvet,dwarf,dweeb,dwell,dwelt,dyads
21340 data dyers,dying,dykes,dynes,eager,eagle,eared,earls,early,earns,earth
21350 data eased,easel,eases,easts,eaten,eater,eaves,ebbed,ebony,echos,eclat
21360 data edema,edged,edger,edges,edict,edify,edits,educe,eerie,egads,egged
21370 data egger,egret,eider,eight,eject,eking,eland,elans,elate,elbow,elder
21380 data elect,elegy,elfin,elide,elite,elope,elude,elves,email,embed,ember
21390 data emcee,emend,emery,emirs,emits,emote,empty,enact,ended,ender,endow
21400 data endue,enema,enemy,enjoy,ennui,enrol,ensue,enter,entry,envoi,envoy
21410 data epact,epees,ephah,ephod,epics,epoch,epoxy,epsom,equal,equip,erase
21420 data erect,erode,erred,error,eruct,erupt,essay,esses,ester,estop,etext
21430 data ether,ethic,ethos,ethyl,etude,evade,evens,event,every,evict,evils
21440 data evoke,exact,exalt,exams,excel,excon,exeat,execs,exert,exile,exist
21450 data exits,expat,expel,expos,extol,extra,exude,exult,exurb,eyers,eying
21460 data eyrie,fable,faced,facer,faces,facet,facie,facto,facts,faddy,faded
21470 data fader,fades,faery,fagot,fails,faint,faire,fairs,fairy,faith,faked
21480 data faker,fakes,fakir,falls,false,famed,fames,fancy,fangs,fanin,fanny
21490 data farad,farce,fared,fares,farms,farts,fasts,fatal,fated,fates,fatly
21500 data fatso,fatty,fatwa,fault,fauna,fauns,favor,fawns,fawny,faxed,faxer
21510 data faxes,fazed,fazes,fears,feast,feats,fecal,feces,feeds,feels,feign
21520 data feint,feist,fella,fells,felon,felts,femme,femur,fence,fends,fenny
21530 data feral,fermi,ferns,ferny,ferry,fetal,fetch,feted,fetes,fetid,fetor
21540 data fetus,feuar,feuds,feued,fever,fewer,fiats,fiber,fibre,fiche,fichu
21550 data fiefs,field,fiend,fiery,fifes,fifth,fifty,fight,filar,filch,filed
21560 data filer,files,filet,fills,filly,films,filmy,filth,final,finch,finds
21570 data fined,finer,fines,finif,finis,finks,finny,fiord,fired,firer,fires
21580 data firma,firms,first,firth,fishy,fists,fisty,fitly,fiver,fives,fixed
21590 data fixer,fixes,fixit,fizzy,fjord,flabs,flack,flags,flail,flair,flake
21600 data flaks,flaky,flame,flams,flank,flaps,flare,flash,flask,flats,flaws
21610 data flays,fleas,fleck,flees,fleet,flesh,flick,flics,flied,flier,flies
21620 data fling,flint,flips,flirt,flits,float,flock,floes,flogs,flood,floor
21630 data flops,flora,floss,flour,flout,flown,flows,flubs,flues,fluff,fluid
21640 data fluke,fluky,flume,flung,flunk,flush,flute,flyby,flyer,foals,foams
21650 data foamy,focal,focus,fogey,foggy,foils,foist,folds,folia,folic,folio
21660 data folks,folky,folly,fondu,fonts,foods,fools,foots,foray,force,fords
21670 data fores,forge,forgo,forks,forky,forma,forms,forte,forth,forts,forty
21680 data forum,fossa,fosse,fouls,found,fount,fours,fovea,fowls,foxed,foxes
21690 data foyer,frail,frame,franc,frank,frats,fraud,frays,freak,freed,freer
21700 data frees,fresh,frets,friar,fried,frier,fries,frigs,frill,frisk,frizz
21710 data frock,frogs,frond,front,frosh,frost,froth,frown,froze,fruit,frump
21720 data fryer,ftped,fucks,fudge,fudgy,fuels,fugal,fugit,fugue,fulls,fully
21730 data fumed,fumer,fumes,funds,fungi,fungo,funks,funky,funny,furls,furor
21740 data furry,furze,fused,fusee,fuses,fussy,fusty,futon,fuzed,fuzes,fuzzy
21750 data gabby,gable,gaffe,gaffs,gages,gaily,gains,gaits,galas,gales,galls
21760 data gamba,gamed,gamer,games,gamey,gamic,gamin,gamma,gamut,ganef,gangs
21770 data gaols,gaped,gaper,gapes,gappy,garbs,garde,gases,gasps,gassy,gated
21780 data gates,gator,gaudy,gauge,gaunt,gauss,gauze,gauzy,gavel,gawks,gawky
21790 data gayer,gayly,gazed,gazer,gazes,gears,gecko,geeks,geese,gelds,genes
21800 data genet,genie,genii,genre,gents,genus,geode,geoid,germs,gesso,getup
21810 data ghost,ghoti,ghoul,giant,gibed,giber,gibes,giddy,gifts,gigas,gigue
21820 data gilds,gills,gilts,gimel,gimme,gimps,gimpy,ginny,gipsy,girds,girls
21830 data girly,giros,girth,girts,gismo,gists,given,giver,gives,gizmo,glade
21840 data glads,gland,glans,glare,glary,glass,glaze,gleam,glean,glebe,glees
21850 data glens,glide,glint,glitz,gloat,globe,globs,gloms,gloom,glory,gloss
21860 data glove,glows,glued,gluer,glues,gluey,gluon,gluts,glyph,gnarl,gnash
21870 data gnats,gnaws,gnome,goads,goals,goats,godly,goers,goest,goeth,gofer
21880 data going,golds,golem,golfs,golly,gonad,goner,gongs,gonna,gonzo,goods
21890 data goody,gooey,goofs,goofy,gooks,gooky,goons,goony,goopy,goose,goosy
21900 data gored,gores,gorge,gorse,goths,gotta,gouda,gouge,gourd,gouts,gouty
21910 data gowns,goyim,grabs,grace,grade,grads,graft,grail,grain,grams,grand
21920 data grant,grape,graph,grapy,grasp,grass,grata,grate,grave,gravy,grays
21930 data graze,great,grebe,greed,greek,green,greet,greps,greys,grids,grief
21940 data grift,grill,grime,grimy,grind,grins,gripe,grips,grist,grits,groan
21950 data groat,grody,grogs,groin,groks,gronk,grook,groom,grope,gross,group
21960 data grout,grove,growl,grown,grows,grubs,gruel,gruff,grump,grunt,guano
21970 data guard,guava,guess,guest,guide,guild,guile,guilt,guise,gulag,gulch
21980 data gules,gulfs,gulls,gully,gulps,gumbo,gummy,gunks,gunky,gunny,guppy
21990 data gurus,gushy,gusto,gusts,gusty,gutsy,gutta,gutty,guyed,gwine,gyppy
22000 data gypsy,gyros,gyved,gyves,habit,hacks,hadda,hades,hadst,hafta,hafts
22010 data haiku,hails,hairs,hairy,haled,haler,hales,hallo,halls,halma,halos
22020 data halts,halve,hames,hammy,hamza,hands,handy,hangs,hanks,hanky,hapax
22030 data haply,happy,hardy,harem,hares,harks,harms,harps,harpy,harry,harsh
22040 data harts,harum,hasps,haste,hasty,hatch,hated,hater,hates,hauls,haunt
22050 data haute,haven,haves,havoc,hawed,hawks,hayed,hayer,hayey,hazed,hazel
22060 data hazer,hazes,heads,heady,heals,heaps,heard,hears,heart,heath,heats
22070 data heave,heavy,hedge,heeds,heels,heerd,hefts,hefty,heigh,heirs,heist
22080 data helix,hello,hells,helms,helps,hemps,hempy,hence,henge,henna,henry
22090 data herbs,herby,herds,herem,heres,heron,heros,hertz,hewed,hewer,hexad
22100 data hexed,hexer,hexes,hicks,hider,hides,highs,hiked,hiker,hikes,hilar
22110 data hills,hilly,hilts,hilum,himbo,hinds,hinge,hints,hippo,hippy,hired
22120 data hirer,hires,hitch,hived,hiver,hives,hoagy,hoard,hoars,hoary,hobby
22130 data hobos,hocks,hocus,hodad,hoers,hogan,hoist,hokey,hokum,holds,holed
22140 data holer,holes,holey,holly,holon,homed,homer,homes,homey,homme,homos
22150 data honed,honer,hones,honey,honks,honky,honor,hooch,hoods,hooey,hoofs
22160 data hooks,hooky,hoops,hoots,hoped,hoper,hopes,hoppy,horde,horns,horny
22170 data horse,horsy,hosed,hoses,hosts,hotel,hotly,hound,houri,hours,house
22180 data hovel,hover,howdy,howls,hubba,hubby,huffs,huffy,huger,hulas,hulks
22190 data hulky,hullo,hulls,human,humid,humor,humpf,humph,humps,humpy,humus
22200 data hunch,hunks,hunky,hunts,hurls,hurly,hurry,hurts,husks,husky,hussy
22210 data hutch,huzza,hydra,hydro,hyena,hying,hymen,hymns,hyped,hyper,hypes
22220 data hypos,iambs,icers,ichor,icier,icily,icing,icons,ideal,ideas,idiom
22230 data idiot,idled,idler,idles,idols,idyll,idyls,igloo,ikats,ikons,ileum
22240 data ileus,iliac,ilium,image,imago,imams,imbed,imbue,immix,impel,imply
22250 data impro,inane,inapt,incur,index,indie,inept,inert,infer,infix,infra
22260 data ingot,injun,inked,inker,inlay,inlet,inner,inode,input,inset,inter
22270 data intra,intro,inure,ioctl,iodic,ionic,iotas,irate,irked,irons,irony
22280 data isles,islet,issue,itchy,items,ivied,ivies,ivory,ixnay,jacks,jaded
22290 data jades,jaggy,jails,jakes,jambs,jammy,janes,japan,jaunt,jawed,jazzy
22300 data jeans,jeeps,jeers,jello,jells,jelly,jenny,jerks,jerky,jerry,jests
22310 data jetty,jewel,jibed,jiber,jibes,jiffs,jiffy,jihad,jilts,jimmy,jingo
22320 data jings,jinks,jinns,jived,jives,jocks,joeys,johns,joins,joint,joist
22330 data joked,joker,jokes,jolly,jolts,joule,joust,jowls,jowly,joyed,judge
22340 data judos,juice,juicy,jujus,jukes,julep,jumbo,jumps,jumpy,junco,junks
22350 data junky,junta,juror,juste,jutes,kabob,kaiak,kales,kapok,kappa,kaput
22360 data karat,karma,kayak,kayos,kazoo,kebab,kebob,keels,keens,keeps,kefir
22370 data kelly,kelps,kelpy,kenaf,kepis,kerbs,kerfs,kerns,ketch,keyed,keyer
22380 data khaki,khans,kicks,kicky,kiddo,kikes,kills,kilns,kilos,kilts,kilty
22390 data kinda,kinds,kings,kinks,kinky,kiosk,kirks,kited,kites,kiths,kitty
22400 data kivas,kiwis,klieg,kluge,klugy,klunk,klutz,knack,knave,knead,kneed
22410 data kneel,knees,knell,knelt,knife,knish,knits,knobs,knock,knoll,knops
22420 data knots,knout,known,knows,knurl,koala,koine,kooks,kooky,kopek,kraal
22430 data kraut,krill,krona,krone,kudos,kudzu,kulak,kyrie,label,labia,labor
22440 data laced,lacer,laces,lacey,lacks,laded,laden,lades,ladle,lager,laird
22450 data lairs,laity,laker,lakes,lamas,lambs,lamed,lamer,lames,lamps,lanai
22460 data lance,lands,lanes,lanky,lapel,lapin,lapis,lapse,larch,lards,lardy
22470 data large,largo,larks,larva,lased,laser,lases,lasso,lasts,latch,later
22480 data latex,lathe,laths,latin,latus,laude,lauds,laugh,lavas,laved,laver
22490 data laves,lawns,lawny,lawzy,laxer,laxly,layer,layup,lazed,lazes,leach
22500 data leads,leafs,leafy,leaks,leaky,leans,leant,leaps,leapt,learn,lease
22510 data leash,least,leave,ledge,leech,leeks,leers,leery,lefts,lefty,legal
22520 data leggo,leggy,legit,legos,lemma,lemme,lemon,lemur,lends,lento,leper
22530 data lepta,letup,levee,level,lever,levis,liars,libel,libra,licit,licks
22540 data liege,liens,liers,liest,lieth,lifer,lifts,light,ligne,liked,liken
22550 data liker,likes,lilac,lilts,lilty,limbo,limbs,limby,limed,limen,limes
22560 data limey,limit,limns,limos,limps,lined,linen,liner,lines,lingo,lings
22570 data links,lints,linty,lions,lipid,lippy,liras,lisle,lisps,lists,liter
22580 data lites,lithe,litho,litre,lived,liven,liver,lives,livid,livre,llama
22590 data loads,loafs,loams,loamy,loans,loath,lobar,lobby,lobed,lobes,local
22600 data lochs,locks,locos,locus,lodes,lodge,loess,lofts,lofty,loges,loggy
22610 data logic,login,logos,loins,lolls,lolly,loner,longs,looks,looky,looms
22620 data loons,loony,loops,loopy,loose,loots,loped,loper,lopes,loppy,lords
22630 data lordy,lores,lorry,loser,loses,lossy,lotsa,lotta,lotto,lotus,louis
22640 data louse,lousy,louts,loved,lover,loves,lowed,lower,lowly,loxes,loyal
22650 data luaus,lubes,lubra,lucid,lucks,lucky,lucre,lulab,lulls,lulus,lumen
22660 data lumps,lumpy,lunar,lunch,lunes,lunge,lungs,lupus,lurch,lured,lurer
22670 data lures,lurid,lurks,lusts,lusty,luted,lutes,luvya,luxes,lycra,lying
22680 data lymph,lynch,lyres,lyric,macaw,maced,macer,maces,macho,macro,madam
22690 data madly,mafia,magic,magma,magna,magus,mahua,maids,mails,maims,mains
22700 data maize,major,maker,makes,males,malls,malts,malty,mamas,mambo,mamma
22710 data mammy,maned,manes,mange,mango,mangy,mania,manic,manly,manna,manor
22720 data manse,manta,maple,march,mares,marge,maria,marks,marls,marry,marsh
22730 data marts,maser,mashy,masks,mason,masse,masts,match,mated,mater,mates
22740 data matey,maths,matte,matzo,mauls,mauve,maven,mavis,maxim,maxis,maybe
22750 data mayor,mayst,mazed,mazer,mazes,meads,meals,mealy,means,meant,meany
22760 data meats,meaty,mebbe,mecca,mecum,medal,media,medic,meets,melba,melds
22770 data melee,melon,melts,memes,memos,mends,menus,meows,mercy,merge,merit
22780 data merry,merse,mesas,mesne,meson,messy,metal,meted,meter,metes,metre
22790 data metro,mewed,mezzo,miaow,micas,micks,micro,middy,midis,midst,miens
22800 data miffs,might,miked,mikes,milch,miler,miles,milks,milky,mills,mimed
22810 data mimeo,mimer,mimes,mimic,mimsy,minas,mince,minds,mined,miner,mines
22820 data minim,minis,minks,minor,mints,minus,mired,mires,mirth,miser,missy
22830 data mists,misty,miter,mites,mitre,mitts,mixed,mixer,mixes,mixup,moans
22840 data moats,mocha,mocks,modal,model,modem,modes,modus,mogul,mohel,moire
22850 data moist,molal,molar,molas,molds,moldy,moles,molls,molly,molto,molts
22860 data momma,mommy,monad,mondo,money,monic,monks,monte,month,mooch,moods
22870 data moody,mooed,moola,moons,moony,moors,moose,moots,moped,moper,mopes
22880 data moral,moray,morel,mores,morns,moron,morph,morts,mosey,mossy,mosts
22890 data motel,motes,motet,moths,mothy,motif,motor,motto,mould,moult,mound
22900 data mount,mourn,mouse,mousy,mouth,moved,mover,moves,movie,mowed,mower
22910 data moxie,mrads,mucho,mucks,mucky,mucus,muddy,muffs,mufti,muggy,mujik
22920 data mulch,mulct,mules,muley,mulls,mumbo,mummy,mumps,munch,munge,mungs
22930 data mungy,muons,mural,murks,murky,mused,muser,muses,mushy,music,musks
22940 data musky,musos,mussy,musta,musts,musty,muted,muter,mutes,mutts,muxes
22950 data mylar,mynah,mynas,myrrh,myths,nabla,nabob,nacho,nadir,naiad,nails
22960 data naive,naked,named,namer,names,nanny,napes,nappy,narco,narcs,nards
22970 data nares,nasal,nasty,natal,natch,nates,natty,naval,navel,naves,nears
22980 data neath,neato,necks,needs,needy,negro,neigh,neons,nerds,nerdy,nerfs
22990 data nerts,nerve,nervy,nests,never,newel,newer,newly,newsy,newts,nexus
23000 data nicad,nicer,niche,nicks,niece,nifty,night,nihil,nimbi,nines,ninja
23010 data ninny,ninth,nippy,nisei,niter,nitro,nitty,nixed,nixes,nixie,nobby
23020 data noble,nobly,nodal,noddy,nodes,noels,nohow,noire,noise,noisy,nomad
23030 data nonce,nones,nonny,nooks,nooky,noons,noose,norms,north,nosed,noses
23040 data nosey,notch,noted,noter,notes,nouns,novae,novas,novel,noway,nuder
23050 data nudes,nudge,nudie,nuked,nukes,nulls,numbs,nurbs,nurse,nutsy,nutty
23060 data nylon,nymph,oaken,oakum,oared,oases,oasis,oaten,oaths,obeah,obese
23070 data obeys,obits,oboes,occur,ocean,ocher,ochre,octal,octet,odder,oddly
23080 data odium,odors,odour,offal,offed,offen,offer,often,ogled,ogler,ogles
23090 data ogres,ohhhh,ohmic,oiled,oiler,oinks,oinky,okapi,okays,okras,olden
23100 data older,oldie,oleos,olios,olive,ombre,omega,omens,omits,oncet,onion
23110 data onset,oodle,oomph,oozed,oozes,opals,opens,opera,opine,opium,opted
23120 data optic,orals,orate,orbed,orbit,orcas,order,organ,oring,orlon,ortho
23130 data osier,other,otter,ought,ouija,ounce,ousel,ousts,outdo,outen,outer
23140 data outgo,outta,ouzel,ovals,ovary,ovate,ovens,overs,overt,ovoid,ovule
23150 data owest,oweth,owing,owlet,owned,owner,oxbow,oxeye,oxide,oxlip,ozone
23160 data paced,pacer,paces,packs,pacts,paddy,padre,paean,pagan,paged,pager
23170 data pages,pails,pains,paint,pairs,paled,paler,pales,palls,pally,palms
23180 data palmy,palsy,pampa,panda,paned,panel,panes,panga,pangs,panic,pansy
23190 data pants,panty,papal,papas,papaw,paper,pappy,paras,parch,pards,pared
23200 data paren,parer,pares,parka,parks,parry,parse,parts,party,pasha,passe
23210 data pasta,paste,pasts,pasty,patch,paten,pater,pates,paths,patio,patsy
23220 data patty,pause,pavan,paved,paver,paves,pawed,pawer,pawky,pawls,pawns
23230 data payed,payee,payer,peace,peach,peaks,peaky,peals,pearl,pears,pease
23240 data peats,peaty,pecan,pecks,pedal,peeks,peels,peens,peeps,peers,peeve
23250 data pekoe,pelts,penal,pence,pends,penes,pengo,penis,penny,peons,peony
23260 data peppy,perch,perdu,peril,perks,perky,perms,pesky,pesos,pesto,pests
23270 data petal,peter,petit,petri,petty,pewee,pewit,pffft,phage,phase,phial
23280 data phlox,phone,phony,photo,phyla,piano,picas,picks,picky,picot,piece
23290 data piers,pieta,piety,piggy,pigmy,piing,piker,pikes,pilaf,pilau,piled
23300 data piles,pills,pilot,pimps,pinch,pined,pines,piney,pings,pinko,pinks
23310 data pinky,pinto,pints,pinup,pions,pious,piped,piper,pipes,pipet,pique
23320 data pismo,pitas,pitch,piths,pithy,piton,pivot,pixel,pixie,pizza,place
23330 data plaid,plain,plait,plane,plank,plans,plant,plash,plasm,plate,plats
23340 data playa,plays,plaza,plead,pleas,pleat,plebe,plebs,plein,plena,plied
23350 data plies,plink,plods,plonk,plops,plots,plows,ploys,pluck,plugs,plumb
23360 data plume,plump,plums,plumy,plunk,plush,plyer,poach,pocks,pocky,podgy
23370 data podia,poems,poesy,poets,point,poise,poked,poker,pokes,pokey,polar
23380 data poled,poler,poles,polio,polis,polka,polls,polly,polos,polyp,pomps
23390 data ponds,pones,pooch,pooey,poohs,pools,poops,popes,poppy,porch,pored
23400 data pores,porgy,porks,porky,porno,ports,posed,poser,poses,poset,posit
23410 data posse,poste,posts,potty,pouch,poufs,pound,pours,pouts,power,poxed
23420 data poxes,prams,prank,prate,prats,prawn,prays,preen,preps,press,prest
23430 data prexy,preys,price,prick,pride,pried,prier,pries,prigs,prima,prime
23440 data primo,primp,prims,prink,print,prior,prise,prism,privy,prize,probe
23450 data prods,proem,profs,promo,proms,prone,prong,proof,props,prose,prosy
23460 data proud,prove,prowl,prows,proxy,prude,prune,pruta,pryer,psalm,pseud
23470 data pshaw,psoas,pssst,psych,pubes,pubic,pubis,pucks,pudgy,puffs,puffy
23480 data puked,pukes,pukka,pulls,pulps,pulpy,pulse,pumas,pumps,punch,punks
23490 data punky,punny,punts,pupae,pupal,pupas,pupil,puppy,puree,purer,purge
23500 data purls,purrs,purse,purty,pushy,pussy,putts,putty,pygmy,pylon,pyres
23510 data pyxie,qophs,quack,quads,quaff,quail,quais,quake,qualm,quals,quark
23520 data quart,quash,quasi,quays,queen,queer,quell,query,quest,queue,quick
23530 data quids,quiet,quiff,quill,quilt,quint,quips,quipu,quire,quirk,quirt
23540 data quite,quits,quoin,quoit,quota,quote,quoth,rabbi,rabid,raced,racer
23550 data races,racks,radar,radii,radio,radix,radon,rafts,raged,rages,raids
23560 data rails,rains,rainy,raise,rajah,rajas,raked,raker,rakes,rally,ramps
23570 data ranch,rands,randy,range,rangy,ranks,rants,raped,raper,rapes,rapid
23580 data rarer,rasae,rasps,raspy,rated,rater,rates,raths,ratio,ratty,raved
23590 data ravel,raven,raver,raves,rawer,rawly,rayed,rayon,razed,razer,razes
23600 data razor,reach,react,reads,ready,realm,reals,reams,reaps,rearm,rears
23610 data rebar,rebel,rebid,rebox,rebus,rebut,recap,recta,recto,recur,recut
23620 data redid,redip,redly,redox,redux,reeds,reedy,reefs,reeks,reeky,reels
23630 data reeve,refer,refit,refix,refly,refry,regal,rehab,reify,reign,reins
23640 data relax,relay,relet,relic,reman,remap,remit,remix,renal,rends,renew
23650 data rente,rents,repay,repel,reply,repro,reran,rerun,resaw,resay,reset
23660 data resew,resin,rests,retch,retro,retry,reuse,revel,revet,revue,rewed
23670 data rheas,rheum,rhino,rhumb,rhyme,rials,ribby,riced,ricer,rices,rider
23680 data rides,ridge,ridgy,rifer,rifle,rifts,right,rigid,rigor,riled,riles
23690 data rille,rills,rimed,rimer,rimes,rinds,rings,rinks,rinse,riots,ripen
23700 data riper,risen,riser,rises,risks,risky,rites,ritzy,rival,rived,riven
23710 data river,rives,rivet,roach,roads,roams,roans,roars,roast,robed,robes
23720 data robin,roble,robot,rocks,rocky,rodeo,roger,rogue,roids,roils,roily
23730 data roles,rolls,roman,romps,rondo,roods,roofs,rooks,rooky,rooms,roomy
23740 data roost,roots,rooty,roped,roper,ropes,roses,rosin,rotor,rouge,rough
23750 data round,rouse,roust,route,routs,roved,rover,roves,rowan,rowdy,rowed
23760 data rower,royal,rubes,ruble,ruche,ruddy,ruder,ruffs,rugby,ruing,ruins
23770 data ruled,ruler,rules,rumba,rumen,rummy,rumor,rumps,runes,rungs,runic
23780 data runny,runts,runty,rupee,rural,ruses,rusks,russe,rusts,rusty,rutty
23790 data saber,sable,sabra,sabre,sacks,sadly,safer,safes,sagas,sager,sages
23800 data sahib,sails,saint,saith,sakes,salad,sales,sally,salon,salsa,salts
23810 data salty,salve,salvo,samba,sands,sandy,saner,sappy,saran,sarge,saris
23820 data sassy,sated,sates,satin,satyr,sauce,saucy,sauna,saute,saved,saver
23830 data saves,savor,savvy,sawed,sawer,saxes,sayer,scabs,scads,scald,scale
23840 data scalp,scaly,scamp,scams,scans,scant,scare,scarf,scarp,scars,scary
23850 data scats,scene,scent,schmo,schwa,scion,scoff,scold,scone,scoop,scoot
23860 data scope,scops,score,scorn,scour,scout,scowl,scows,scram,scrap,screw
23870 data scrim,scrip,scrod,scrub,scrum,scuba,scudi,scudo,scuds,scuff,scull
23880 data scums,scurf,scuse,scuzz,seals,seams,seamy,sears,seats,sebum,secco
23890 data sects,sedan,seder,sedge,sedgy,sedum,seeds,seedy,seeks,seems,seeps
23900 data seers,seest,seeth,segue,seine,seize,selah,selfs,sells,semen,semis
23910 data sends,sense,sepal,sepia,sepoy,septa,serfs,serge,serif,serum,serve
23920 data servo,setup,seven,sever,sewed,sewer,sexed,sexes,shack,shade,shads
23930 data shady,shaft,shags,shahs,shake,shako,shaky,shale,shall,shalt,shame
23940 data shams,shank,shape,shard,share,shark,sharp,shave,shawl,shawm,shays
23950 data sheaf,shear,sheds,sheen,sheep,sheer,sheet,sheik,shelf,shell,sherd
23960 data shews,shied,shier,shies,shift,shiki,shill,shims,shine,shins,shiny
23970 data ships,shire,shirk,shirr,shirt,shish,shits,shlep,shmoo,shnor,shoal
23980 data shoat,shock,shoed,shoer,shoes,shoji,shone,shook,shoos,shoot,shops
23990 data shore,shorn,short,shots,shout,shove,shown,shows,showy,shred,shrew
24000 data shrub,shrug,shuck,shuns,shunt,shush,shute,shuts,shyer,shyly,sibyl
24010 data sicko,sicks,sided,sides,sidle,siege,sieve,sifts,sighs,sight,sigma
24020 data signs,silks,silky,sills,silly,silos,silts,silty,since,sines,sinew
24030 data singe,sings,sinks,sinus,sired,siree,siren,sires,sirup,sisal,sissy
24040 data sitar,sited,sites,situs,sixes,sixth,sixty,sized,sizer,sizes,skate
24050 data skeet,skein,skews,skids,skied,skier,skies,skiff,skill,skimp,skims
24060 data skins,skint,skips,skirt,skits,skoal,skulk,skull,skunk,skyed,slabs
24070 data slack,slags,slain,slake,slams,slang,slant,slaps,slash,slate,slats
24080 data slave,slaws,slays,sleds,sleek,sleep,sleet,slept,slews,slice,slick
24090 data slide,slier,slily,slime,slims,slimy,sling,slink,slips,slits,slobs
24100 data sloes,slogs,slomo,sloop,slope,slops,slosh,sloth,slots,slows,slued
24110 data slues,sluff,slugs,slump,slums,slung,slunk,slurp,slurs,slush,sluts
24120 data slyer,slyly,smack,small,smart,smash,smear,smell,smelt,smile,smirk
24130 data smite,smith,smock,smogs,smoke,smoky,smote,smurf,smuts,snack,snafu
24140 data snags,snail,snake,snaky,snaps,snare,snarf,snark,snarl,sneak,sneer
24150 data snide,sniff,snipe,snips,snits,snobs,snood,snook,snoop,snoot,snore
24160 data snort,snots,snout,snows,snowy,snubs,snuck,snuff,snugs,soaks,soaps
24170 data soapy,soars,sober,socko,socks,socle,sodas,sofas,softs,softy,soggy
24180 data soils,solar,soled,soles,solid,solon,solos,solum,solve,somas,sonar
24190 data songs,sonic,sonly,sonny,sooth,soots,sooty,soppy,sorer,sores,sorry
24200 data sorta,sorts,souls,sound,soups,soupy,sours,souse,south,sowed,sower
24210 data soyas,space,spacy,spade,spake,spang,spank,spans,spare,spark,spars
24220 data spasm,spate,spats,spawn,spays,spazz,speak,spear,speck,specs,speed
24230 data spell,spelt,spend,spent,sperm,spews,spice,spics,spicy,spied,spiel
24240 data spier,spies,spiff,spike,spiky,spill,spilt,spina,spine,spins,spiny
24250 data spire,spite,spits,spitz,spivs,splat,splay,split,spoil,spoke,spoof
24260 data spook,spool,spoon,spoor,spore,sport,spots,spout,sprat,spray,spree
24270 data sprig,sprit,sprog,sprue,spuds,spued,spume,spumy,spunk,spurn,spurs
24280 data spurt,sputa,squab,squad,squat,squaw,squib,squid,stabs,stack,staff
24290 data stage,stags,stagy,staid,stain,stair,stake,stale,stalk,stall,stamp
24300 data stand,stank,staph,stare,stark,stars,start,stash,state,stats,stave
24310 data stays,stead,steak,steal,steam,steed,steel,steep,steer,stein,stela
24320 data stele,stems,steno,steps,stern,stets,stews,stick,stied,sties,stiff
24330 data stile,still,stilt,sting,stink,stint,stirs,stoae,stoas,stoat,stock
24340 data stogy,stoic,stoke,stole,stoma,stomp,stone,stony,stood,stool,stoop
24350 data stops,store,stork,storm,story,stoup,stout,stove,stows,strap,straw
24360 data stray,strep,strew,strip,strop,strum,strut,stubs,stuck,studs,study
24370 data stuff,stump,stung,stunk,stuns,stunt,styes,style,styli,suave,sucks
24380 data sudsy,suede,suers,suets,suety,sugar,suing,suite,suits,sulfa,sulks
24390 data sulky,sully,sumac,summa,sumps,sunny,sunup,super,supes,supra,suras
24400 data surds,surer,surfs,surge,surly,sushi,sutra,swabs,swags,swain,swami
24410 data swamp,swank,swans,swaps,sward,sware,swarf,swarm,swart,swash,swath
24420 data swats,sways,swear,sweat,swede,sweep,sweet,swell,swept,swift,swigs
24430 data swill,swims,swine,swing,swipe,swirl,swish,swiss,swive,swoon,swoop
24440 data sword,swore,sworn,swung,sylph,synch,syncs,synod,syrup,tabby,table
24450 data taboo,tabor,tabus,tacet,tacit,tacks,tacky,tacos,tacts,taels,taffy
24460 data tagua,tails,taint,taken,taker,takes,talcs,tales,talks,talky,tally
24470 data talon,talus,tamed,tamer,tames,tamps,tango,tangs,tangy,tanks,tansy
24480 data taped,taper,tapes,tapir,tapis,tardy,tared,tares,tarns,taros,tarot
24490 data tarps,tarry,tarts,tasks,taste,tasty,tater,tatty,taunt,taupe,tawny
24500 data taxed,taxer,taxes,taxis,taxol,taxon,teach,teaks,teals,teams,tears
24510 data teary,tease,teats,techs,techy,tecum,teddy,teems,teens,teeny,teeth
24520 data telex,tells,telly,tempi,tempo,temps,tempt,tench,tends,tenet,tenon
24530 data tenor,tense,tenth,tents,tepee,tepid,terce,terms,terns,terra,terry
24540 data terse,tesla,tests,testy,tetra,texas,texts,thane,thank,thanx,thats
24550 data thaws,thees,theft,their,theme,thens,there,therm,these,theta,thews
24560 data thick,thief,thigh,thine,thing,think,thins,third,thong,thorn,those
24570 data thous,three,threw,throb,throe,throw,thrum,thuds,thugs,thumb,thump
24580 data thunk,thwap,thyme,tiara,tibia,ticks,tidal,tided,tides,tiers,tiffs
24590 data tiger,tight,tikes,tikis,tilde,tiled,tiler,tiles,tills,tilth,tilts
24600 data timed,timer,times,timid,tines,tinge,tings,tinny,tints,tippy,tipsy
24610 data tired,tires,tiros,titan,titer,tithe,title,titre,titty,tizzy,toads
24620 data toady,toast,today,toddy,toffs,toffy,togas,toile,toils,toked,token
24630 data toker,tokes,tolls,tombs,tomes,tommy,tonal,toned,toner,tones,tongs
24640 data tonic,tools,toons,tooth,toots,topaz,toped,toper,topes,topic,topoi
24650 data topos,toque,torah,torch,toric,torsi,torso,torte,torts,torus,total
24660 data toted,totem,toter,totes,totty,touch,tough,tours,touts,toves,towed
24670 data towel,tower,towns,toxic,toxin,toyed,toyer,toyon,trace,track,tract
24680 data trade,trail,train,trait,tramp,trams,trans,traps,trash,trawl,trays
24690 data tread,treap,treat,treed,trees,treks,trend,tress,trews,treys,triad
24700 data trial,tribe,tribs,trice,trick,tried,trier,tries,trike,trill,trims
24710 data trios,tripe,trips,trite,troll,tromp,troop,troth,trots,trout,trove
24720 data trows,truce,truck,trued,truer,trues,truly,trump,trunk,truss,trust
24730 data truth,tryst,tsars,tuans,tubal,tubas,tubby,tubed,tuber,tubes,tucks
24740 data tufas,tufts,tufty,tulip,tulle,tummy,tumor,tunas,tuned,tuner,tunes
24750 data tunic,tunny,tuple,turbo,turds,turdy,turfs,turfy,turns,turps,tusks
24760 data tusky,tutor,tutti,tutus,tuxes,twain,twang,twats,tweak,tweed,tweet
24770 data twerp,twice,twigs,twill,twine,twink,twins,twiny,twirl,twirp,twist
24780 data twits,twixt,tying,tykes,typal,typed,types,typos,tyres,tyros,tzars
24790 data udder,ukase,ulcer,ulnar,ulnas,ultra,umbel,umber,umbra,umiak,umped
24800 data umpty,unapt,unarc,unarm,unary,unate,unban,unbar,unbox,uncap,uncle
24810 data uncut,under,undid,undue,unfed,unfit,unfix,unhip,unhit,unify,union
24820 data unite,units,unity,unjam,unlit,unman,unmap,unmet,unpeg,unpin,unrig
24830 data unsay,unsee,unset,unsew,unsex,untie,until,unwed,unwon,unzip,upend
24840 data upped,upper,upset,urban,ureas,urged,urger,urges,urine,usage,users
24850 data usher,using,usual,usurp,usury,uteri,utero,utter,uvula,vacua,vacuo
24860 data vague,vagus,vails,vales,valet,valid,valor,value,valve,vamps,vaned
24870 data vanes,vapes,vapid,vapor,varia,vases,vault,vaunt,veals,veeps,veers
24880 data vegan,veils,veins,veiny,velar,velds,veldt,venal,vends,venom,vents
24890 data venue,verbs,verge,versa,verse,verso,verst,verve,vests,vetch,vexed
24900 data vexes,vials,viand,vibes,vicar,vices,video,viers,views,vigil,vigor
24910 data viler,villa,ville,villi,vinca,vined,vines,vinyl,viola,viols,viper
24920 data viral,vireo,vires,virus,visas,vised,vises,visit,visor,vista,vitae
24930 data vital,vitam,vitas,vitro,vivas,vivid,vivre,vixen,vizor,vocab,vocal
24940 data vodka,vogue,voice,voids,voila,voile,volts,vomit,voted,voter,votes
24950 data vouch,vowed,vowel,vower,voxel,vroom,vulva,vying,wacko,wacky,waded
24960 data wader,wades,wadis,wafer,wafts,waged,wager,wages,wagon,wahoo,waifs
24970 data wails,waist,waits,waive,waked,waken,waker,wakes,waled,wales,walks
24980 data walls,waltz,wands,waned,wanes,wanly,wanna,wanta,wants,wards,wares
24990 data warms,warns,warps,warts,warty,washy,wasps,waspy,wassa,waste,watch
25000 data water,watsa,watts,waved,waver,waves,waxed,waxen,waxer,waxes,wazoo
25010 data weald,weals,weans,wears,weary,weave,webby,weber,wedge,wedgy,weeds
25020 data weedy,weeks,weeny,weeps,weepy,weest,wefts,weigh,weird,weirs,welch
25030 data welds,wells,welsh,welts,wench,wends,wests,wetly,whack,whale,whams
25040 data whang,wharf,whats,wheal,wheat,wheee,wheel,whelk,whelm,whelp,whens
25050 data where,whets,whews,wheys,which,whiff,while,whims,whine,whiny,whips
25060 data whipt,whirl,whirr,whirs,whish,whisk,whist,white,whits,whizz,whoas
25070 data whole,whomp,whooo,whoop,whops,whore,whorl,whose,whoso,whump,wicks
25080 data widen,wider,widow,width,wield,wifey,wilco,wilds,wiled,wiles,wills
25090 data wilts,wimps,wimpy,wince,winch,winds,windy,wined,wines,winey,wings
25100 data winks,winos,wiped,wiper,wipes,wired,wirer,wires,wised,wiser,wises
25110 data wisps,wispy,wists,witch,withs,witty,wives,wizen,woken,wolds,woman
25120 data wombs,women,wonks,wonky,wonts,woods,woody,wooed,wooer,woofs,wools
25130 data wooly,woosh,woozy,words,wordy,works,world,worms,wormy,worry,worse
25140 data worst,worth,worts,would,wound,woven,wowed,wowee,wrack,wraps,wrath
25150 data wreak,wreck,wrens,wrest,wrier,wring,wrist,write,writs,wrong,wrote
25160 data wroth,wrung,wryer,wryly,wurst,xenon,xerox,xored,xylem,yacht,yahoo
25170 data yanks,yards,yarns,yawed,yawls,yawns,yawny,yawps,yearn,years,yeast
25180 data yecch,yella,yells,yelps,yenta,yerba,yeses,yield,yikes,yipes,yobbo
25190 data yodel,yogas,yogic,yogis,yoked,yokel,yokes,yolks,yolky,yores,young
25200 data yourn,yours,youse,youth,yowls,yoyos,yucca,yucky,yukky,yules,yummy
25210 data yurts,zappy,zayin,zeals,zebra,zebus,zeros,zests,zesty,zetas,zilch
25220 data zincs,zings,zingy,zippy,zloty,zombi,zonal,zoned,zones,zonks,zooey
25230 data zooks,zooms,zowie